---
preservicesrunning:
  - 'getty@tty1.service'
  - 'serial-getty@ttyS0.service'
  - 'firewalld.service'
  - 'acpid.service'
  - 'tuned.service'
  - 'google-network-daemon.service'
  - 'network'
  - 'postfix.service'
  - 'rsyslog.service'
  - 'google-osconfig-agent.service'
  - 'dbus.service'
  - 'systemd-logind.service'
  - 'google-accounts-daemon.service'
  - 'auditd.service'
  - 'crond.service'
  - 'google-clock-skew-daemon.service'
  - 'polkit.service'
  - 'chronyd.service'
  - 'NetworkManager.service'
  - 'systemd-udevd.service'
  - 'sshd.service'
  - 'systemd-journald.service'
