---
postservicesenabled:
  - 'systemd-readahead-collect.service'
  - 'ntpd.service'
  - 'firewalld.service'
  - 'yum-cron.service'
  - 'acpid.service'
  - 'rhel-dmesg.service'
  - 'tuned.service'
  - 'expand-root.service'
  - 'dbus-org.fedoraproject.FirewallD1.service'
  - 'google-startup-scripts.service'
  - 'google-instance-setup.service'
  - 'google-network-daemon.service'
  - 'network'
  - 'postfix.service'
  - 'rsyslog.service'
  - 'NetworkManager-wait-online.service'
  - 'google-osconfig-agent.service'
  - 'qemu-guest-agent.service'
  - 'getty@.service'
  - 'dbus-org.freedesktop.nm-dispatcher.service'
  - 'rhel-autorelabel.service'
  - 'google-accounts-daemon.service'
  - 'rhel-readonly.service'
  - 'auditd.service'
  - 'rhel-domainname.service'
  - 'google-shutdown-scripts.service'
  - 'autovt@.service'
  - 'crond.service'
  - 'google-clock-skew-daemon.service'
  - 'chronyd.service'
  - 'rhel-loadmodules.service'
  - 'rhel-import-state.service'
  - 'rhel-configure.service'
  - 'rhel-autorelabel-mark.service'
  - 'NetworkManager.service'
  - 'systemd-readahead-drop.service'
  - 'NetworkManager-dispatcher.service'
  - 'systemd-readahead-replay.service'
  - 'sshd.service'
