---
- name: install apache
  yum:
    name: httpd
    state: present

- name: create ansible folder inside tomcat folder
  file:
    path: "{{ apache_web_dir }}"
    state: directory

- name: copy static index.html to {{ apache_web_dir }}
  template:
    src: index.html.j2
    dest: "{{ apache_web_dir }}/index.html"
