---
- name: "[set-stats] Playbook 1 - Create downtime and get downtime_id"
  #hosts: all
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:
    - name: "[set-stats] Playbook 1 - Create downtime and get downtime_id"
      set_stats:
        data:
          downtime_id: "61bff285-3390-4211-bf6f-0b684586e22a"
        aggregate: False # default yes and was duplicating/multiplying the string (according to the number of hosts in inventory)
        per_host: False

    - name: "[set-stats] Playbook 1 - Create JSON to set downtime"
      command: ./createJSON.sh

    - name: "[set-stats] Playbook 1 - Create downtime and get downtime_id"
      uri:
        #url: http://op-icinga2-server.manderson-it.team.arctiq.ca:5665/v1/actions/schedule-downtime
        url: https://localhost:5665/v1/actions/schedule-downtime
        url_username: "{{ lookup('env','API_USERNAME') }}"
        url_password: "{{ lookup('env','API_PASSWORD') }}"
        validate_certs: False
        method: "POST"
        body_format: json
        body: "{{ lookup('file','file.json') }}"
        return_content: True
        headers:
          Accept: "application/json"
      register: r_uri
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['icinga2_server'] }}"

    - name: "[set-stats] Playbook 1 - DEBUG"
      debug:
        var: r_uri.results.json
