---
- name: "[set-stats] Playbook 1 - Create downtime and get downtime_id"
  hosts: all
  gather_facts: False
  
  tasks:
    - name: "[set-stats] Playbook 1 - Create downtime and get downtime_id"
      set_stats:
        data:
          downtime_id: "61bff285-3390-4211-bf6f-0b684586e22a"
        aggregate: False # default yes and was duplicating/multiplying the string (according to the number of hosts in inventory)
        per_host: False

    - name: "[set-stats] Playbook 1 - Create JSON to set downtime"
      command: /home/sa_106555649241189152003/createJSON.sh
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['icinga2_server'] }}"

    - name: "[set-stats] Playbook 1 - Create downtime and get downtime_id"
      uri:
        url: https://localhost:5665/v1/actions/schedule-downtime
        method: POST
        user: "{{ lookup('env','API_USERNAME') }}"
        password: "{{ lookup('env','API_PASSWORD') }}"
        src: file.json
        remote_src: True
        return_content: True
      register: r_uri
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['icinga2_server'] }}"

    - name: "[set-stats] Playbook 1 - DEBUG"
      debug:
        var: r_uri
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['icinga2_server'] }}"
