---
- name: Playbook2 - Output set_stats fact set by a different playbook (playbook1_set_stats.yml)
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Playbook2 - Output set_stats fact set by a different playbook
      debug:
        msg: "{{ downtime_id }}"
      run_once: yes # runs only on first host in the inventory or batch, I guess
