---
- name: "[set-stats] Playbook 1 - Create downtime and get downtime_id"
  hosts: all
  gather_facts: False
  
  tasks:
    - name: "[set-stats] Playbook 1 - Create downtime and get downtime_id"
      set_stats:
        data:
          downtime_id: "61bff285-3390-4211-bf6f-0b684586e22a"
        aggregate: False # default yes and was duplicating/multiplying the string (according to the number of hosts in inventory)
        per_host: False
    #- name: "[set-stats] Playbook 1 - Output tower special vars - Workflow (ID is UNDEFINED if variable is undefined)
    #  debug:
    #    msg: "Set by {{ tower_workflow_job_id | default('UNDEFINED') }}. Template: Template: {{ tower_job_template_name | default('UNDEFINED') }}. Workflow: {{ tower_workflow_job_name | default('UNDEFINED') }}."
    #- name: Output tower special vars - Job Template
    #  debug:
    #    msg: "I am job {{ tower_job_id | default('UNDEFINED') }}. Template: {{ tower_job_template_name | default('UNDEFINED') }}."
#tower_job_id
#tower_job_launch_type
#tower_job_template_id
#tower_job_template_name
#tower_user_id
#tower_user_name
#tower_schedule_id
#tower_schedule_name
#tower_workflow_job_id
#tower_workflow_job_name
