---
- name: Play1 - set_stats with a role, then next play will use other role to retrieve it
  hosts: all
  gather_facts: false
  roles:
    - test_set_stats1

- name: Play2 - Play will use other role to retrieve set_stats variable
  hosts: all
  gather_facts: false
  roles:
    - test_set_stats2
