---
- name: "[set-stats] Playbook2 - Get downtime_id from playbook 1 (playbook1_set_stats.yml)"
  hosts: all
  gather_facts: False
  
  tasks:
    - name: "[set-stats] Playbook2 - Get downtime_id from playbook 1 (playbook1_set_stats.yml)"
      debug:
        msg: "{{ downtime_id }}"
      run_once: True # runs only on first host in the inventory or batch, I guess
