---
- name: Get services info from system
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Put services info into host facts
      service_facts:

    - name: Try to loop or query with when
      debug:
        msg: "{{ item }}"
      with_items: ansible_facts.services
