---
- name: Developer Instance - Test Servicenow integration 
  hosts: all
  connection: local
  gather_facts: true # for ansible_date_time to exist
  #ignore_errors: true
  vars:
    #snow_instance: dev60536
    snow_cr: CHG0040001
    app_name: EDRMS

# table: u_ansible_change_ticket_web_service # change_request
  tasks:
    - debug:
        msg:
        - "ServiceNow instance used: {{ lookup('env','SNOW_INSTANCE') }}"
        - "ServiceNow Change Request used: '{{ snow_cr }}'"
      run_once: true
      delegate_to: localhost
        
    - name: WORKS - Update a change request with work_notes risk priority impact
      snow_record:
        username: "{{ lookup('env','SNOW_USERNAME') }}"
        password: "{{ lookup('env','SNOW_PASSWORD') }}"
        instance: "{{ lookup('env','SNOW_INSTANCE') }}"
        number: "{{ snow_cr }}"  #"{{ new_cr.record.number }}"
        state: present
        table: change_request
        data:
          work_notes: "Patching completed for {{ app_name }}.\nSee Workflow {{ tower_workflow_job_name | default('UNDEFINED') }} and Tower job ID {{ tower_workflow_job_id | default('UNDEFINED') }}."
      register: change_cr
      run_once: true
      delegate_to: localhost
# 
#    - name: debug - Edited change_cr Change Request
#      debug:
#        var: change_cr
