---
- name: "[SNOW] - email to work_notes"
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    snow_ref: "Ref:MSG0000062_118fL7liW22H9bIWUcPT"
  
  tasks:
  - name: "[SNOW] - email to work_notes"
    mail:
      host: "{{ lookup('env','MAIL_HOST') }}"
      username: "{{ lookup('env','MAIL_USERNAME') }}"
      password: "{{ lookup('env','MAIL_PASSWORD') }}"
      port: 587
      from: "marek.anderson@arctiq.ca"
      to: "dev97567@servicenowdevelopers.com"
      subject: "Re: {{ snow_cr | default('CHG0030001', true) }}"
      body: "Hey, I am Ansible Tower 3.6. {{ snow_ref | default('', true) }}"
