---
- name: Test Servicenow integration
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    snow_instance: dev60536
    snow_user: admin
    snow_pw: ""
    #snow_chgtask: CTASK0010001 # NON-unique identifier
    snow_chgtask: CTASK0010003 # NON-unique identifier (but only once in my dev instance)
    snow_chgreq: CHG0040001 # unique identifier

  tasks:
  # works
  - name: Create a new change request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_pw }}"
      instance: "{{ snow_instance }}"
      state: present
      table: change_request
      data:
        short_description: "This is a test change_request created by Ansible on {{ ansible_date_time.iso8601 }}"
        description: "Description by Ansible on {{ ansible_date_time.iso8601 }}"
        work_notes: "Work notes by Ansible on {{ ansible_date_time.iso8601 }}"
    register: chgreq_created
#
#  # works
#  - name: debug - newly created change request
#    debug:
#      var: chgreq_created
#
#  # works
#  - name: Get existing change request
#    snow_record:
#      username: "{{ snow_user }}"
#      password: "{{ snow_pw }}"
#      instance: "{{ snow_instance }}"
#      number: "{{ snow_chgreq }}"
#      table: change_request
#      state: present
#    register: chgreq
#
#  # works
#  - name: debug - chgreq data (does it have chgtask as elements)
#    debug:
#      var: chgreq

# python module error if more than one result is returned
# Multiple results for get_one()
#
# fails
  - name: Get existing change task
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_pw }}"
      instance: "{{ snow_instance }}"
      number: "{{ snow_chgtask }}"
      #lookup_field: change_request
      table: change_task # this refers to the Service Catalog task table and is something entirely different
      state: present
      data:
        limit: 1
    register: chgtask

# fails
  - name: debug - chgtask data
    debug:
      var: chgtask

