---
- name: Developer Instance - Test Servicenow integration 
  hosts: localhost
  connection: local
  gather_facts: false # set true for ansible_date_time to exist
  #ignore_errors: true
  vars:
    snow_instance: dev60536
    snow_cr: CHG0040001
    app_name: EDRMS

  roles:
    - snow_error_reporting
