- name: Test reachability of instance nodes
  hosts: all
  ignore_errors: True # to continue with subsequent tasks in case of error
  
  tasks:
    - name: Check instance node status via Tower API /api/v2/ping
      uri:
        url: https://35.202.98.115/api/v2/ping/
        follow_redirects: all
        method: GET
        user: "{{ api_username }}"
        password: "{{ api_password }}"
        validate_certs: False
        status_code: [200, 201, 202]
        return_content: True
      register: result
    - name: DEBUG returned status from API call
      debug:
        var: result.json
    - name: Test - SSH reachability and Python readiness on Tower instance node
      ping:
    - name: Test - Fact gathering on instance node
      setup:
    - name: DEBUG gathered facts from instance node
      debug:
        var: ansible_facts
