---
# variables to create a virtual machine on VMware infrastructure
vmware_vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
vmware_vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
vmware_vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"
vmware_vcenter_datacenter: ""
vmware_vcenter_cluster: ""
vmware_vcenter_datastore: ""

# variables specific to a virtual machine
vmware_vm_name: ""
vmware_vm_folder: "/" # slash as highest folder level
vmware_vm_network: "VM Network"
vmware_vm_template: ""
vmware_vm_annotation: ""
vmware_vm_num_cpus: 1
vmware_vm_memory_mb: 2048
vmware_vm_vlan: 0 


# variables for Infoblox DDI appliance
nios_provider:
  host: "{{ lookup('env','INFOBLOX_HOST') }}"
  username: "{{ lookup('env','INFOBLOX_USERNAME') }}"
  password: "{{ lookup('env','INFOBLOX_PASSWORD') }}"
