---
#- name: Get next available IP address from Infoblox DDI
#  set_fact:
#    ipaddr: "{{ lookup('nios_next_ip', '192.168.10.0/24', provider=nios_provider) }}"
#  delegate_to: localhost
- name: (simulating) Get next available IP address from Infoblox
  set_fact:
    ipaddr: '172.16.42.42'
    ipaddrcidr: '172.16.42.0/29'

- name: Create new virtual machine on VMware
  vmware_guest:
    hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    datacenter: "{{ vmware_vcenter_datacenter }}"
    cluster: "{{ vmware_vcenter_cluster }}" # Is_this_predefined?
    datastore: "{{ vmware_vcenter_datastore }}" # Is_this_predefined?
    name: "{{ vmware_vm_name }}"
    template: "{{ vmware_vm_template }}" # centos76-minimal, rhel7-generic
    annotation: "{{ vmware_vm_annotation }}" # Shows as Notes on VM in vCenter
    folder: "{{ vmware_vm_folder }}" # required
    validate_certs: false
    state: poweredon
    wait_for_ip_address: no
    hardware:
      num_cpus: "{{ vmware_vm_num_cpus }}"
      memory_mb: "{{ vmware_vm_memory_mb }}"
    networks:
    - name: "{{ vmware_vm_network }}" # default: VM Network
      device_type: vmxnet3
      ip: "{{ ipaddr }}"
      netmask: "{{ ipaddrcidr | ipaddr('netmask') }}"
  delegate_to: localhost
  register: vminfo
      
- name: debug var service_id
  debug:
    var: service_id
    
- name: debug ipaddrcidr
  debug:
    var: "{{ ipaddrcidr | ipaddr('netmask') }}"
