---
- name: Generating VM name(s)
  set_fact:
    vmware_vm_names: "{{ vmware_vm_names + [ item ] }}"
  with_sequence: start=1 end="{{ vmware_vm_num }}" format="{{ name_format }}"

- name: debug - list of names for virtual machines
  debug:
    var: vmware_vm_names
