---
- debug:
    msg:
    - "ServiceNow instance used: '{{ lookup('env','SNOW_INSTANCE' }}'"
    - "ServiceNow Change Request used: '{{ snow_cr }}'"
  run_once: true
  delegate_to: localhost

- name: Report error(s) in work_notes in a Change Request
  snow_record:
    username: "{{ lookup('env','SNOW_USERNAME') }}"
    password: "{{ lookup('env','SNOW_PASSWORD') }}"
    instance: "{{ lookup('env','SNOW_INSTANCE') }}"
    number: "{{ snow_cr }}"
    state: present
    table: change_request
    data:
      work_notes: "Error(s) encountered while patching {{ app_name }}. \nSee Workflow {{ tower_workflow_job_name | default('UNDEFINED') }} and Tower job ID {{ tower_workflow_job_id | default('UNDEFINED') }} for details."
  register: change_cr
  run_once: true
  delegate_to: localhost

- name: Set wf_error to true
  set_stats:
    data:
      wf_error: true
    aggregate: no
    per_host: no

- name: Fail this Job Template due to previous Job Template error to reflect correct state
  fail:
    msg: "Fail this Job Template to set Workflow status to failed. Required due to reflect correct state"

