---
#- name: Get next available IP address from Infoblox DDI
#  set_fact:
#    ipaddr: "{{ lookup('nios_next_ip', '192.168.10.0/24', provider=nios_provider) }}"
#  delegate_to: localhost

- name: Retire virtual machine on VMware
  vmware_guest:
    hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    validate_certs: false
    name: "{{ vmware_vm_name }}"
    force: yes # required for VM in poweredOn state
    state: absent
  delegate_to: localhost
